#!/opt/homebrew/bin/python3

from bs4 import BeautifulSoup
# from urllib.request import urlopen
import requests
import re

print("hello")

isbns = ["9781786892737", "9780525538424", "9781474881326", "9781760402501", "9780553804577"]

# link = f"https://www.amazon.com.au/s?k=9781786892737"

for isbn in isbns:
    dimString = ""
    link = f"https://www.amazon.com.au/s?k={isbn}"
    # htmlPage = urlopen(link)
    htmlPage = requests.get(link, headers={"User-Agent":"Defined"})

    soup = BeautifulSoup(htmlPage.content, "html.parser")
    i = 0

    for link in soup.find_all("a", {"class": "a-link-normal s-no-outline"}):
        if i >= 1:
            break

        sublink = link.get("href")
        print(link.get("href"))
        infoLink = f"https://www.amazon.com.au{sublink}"
        print(infoLink)

        # getting the dimensions from amazon
        infoHtml = requests.get(infoLink, headers={"User-Agent":"Defined"})
        infoSoup = BeautifulSoup(infoHtml.content, "html.parser")
        bookInfo = infoSoup.find("ul", {"class": "a-unordered-list a-nostyle a-vertical a-spacing-none detail-bullet-list"})
        descItems = bookInfo.findChildren("li", recursive=False)
        
        for child in descItems:
            # Checks the dimensions text
            if "Dimensions" in child.text:
                print("----------- Child Info -----------")
                # print(child.text.replace('\n', ''))

                dimstr = child.text.replace('\n', '')
                tok = dimstr.split(':')[1]
                # dim = re.split('x ', tok)
                dim = tok.split(' ')
                thickFlag = 0
                dimensions = ""

                for d in dim:
                    if re.match(r'^-?\d+(?:\.\d+)$', d) is None:
                        # print("not float")
                        continue
                    elif thickFlag == 1:
                        # print("ignoring thickness")
                        thickFlag += 1
                    else:
                        # print(d)
                        thickFlag += 1
                        size = int(float(d) * 10)
                        dimensions += str(size) + "*"
                        # print(dimensions)

                # fixing dimensions string
                dimensions = dimensions[:-1]
                dimensions = dimensions.replace('*', " x ")
                dimString = f"{dimensions}mm"

            # Checks for type of book
            # if "back" in child.text or "cover" in child.text:
            if ("back" in child.text) or ("cover" in child.text):
                type = child.text.replace('\n', '')
                type = type.split(':')[0]
                print(type)
            


        i += 1
        # for desc in descItems:
        #     print(desc)

        # for li in infoSoup.find_all("span", {"class": "a-list-item"}):
        #     print(li)

        # print(bookInfo)
    if dimString == "":
        print("find dimensions manually")
    else:
        print(dimString)
    print("hello i would like to apply for a loan")

    print("-------------------------")
    


